name: 'Setup Xvfb'
description: 'Start Xvfb virtual display server'
inputs:
  display:
    description: 'Display number for Xvfb'
    required: false
    default: ':0'
  screen:
    description: 'Screen configuration for Xvfb'
    required: false
    default: '1024x768x24'
  max-attempts:
    description: 'Maximum attempts to wait for Xvfb'
    required: false
    default: '120'
runs:
  using: 'composite'
  steps:
    - name: Start Xvfb
      shell: bash
      run: |
        Xvfb ${{ inputs.display }} -screen 0 ${{ inputs.screen }} > /dev/null 2>&1 &
        # Wait for Xvfb
        MAX_ATTEMPTS=${{ inputs.max-attempts }}
        COUNT=0
        echo -n "Waiting for Xvfb to be ready..."
        while ! xdpyinfo -display "${{ inputs.display }}" >/dev/null 2>&1; do
          echo -n "."
          sleep 0.50s
          COUNT=$(( COUNT + 1 ))
          if [ "${COUNT}" -ge "${MAX_ATTEMPTS}" ]; then
            echo "  Gave up waiting for X server on ${{ inputs.display }}"
            exit 1
          fi
        done
        echo "Done - Xvfb is ready!"
