name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.25"

      - name: Build binaries
        run: |
          # Build for multiple platforms
          GOOS=darwin GOARCH=amd64 go build -o initiat-darwin-amd64 .
          GOOS=darwin GOARCH=arm64 go build -o initiat-darwin-arm64 .
          GOOS=linux GOARCH=amd64 go build -o initiat-linux-amd64 .
          GOOS=linux GOARCH=arm64 go build -o initiat-linux-arm64 .
          GOOS=windows GOARCH=amd64 go build -o initiat-windows-amd64.exe .

          # Create archives
          tar -czf initiat-darwin-amd64.tar.gz initiat-darwin-amd64
          tar -czf initiat-darwin-arm64.tar.gz initiat-darwin-arm64
          tar -czf initiat-linux-amd64.tar.gz initiat-linux-amd64
          tar -czf initiat-linux-arm64.tar.gz initiat-linux-arm64
          zip initiat-windows-amd64.zip initiat-windows-amd64.exe
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            initiat-darwin-amd64.tar.gz
            initiat-darwin-arm64.tar.gz
            initiat-linux-amd64.tar.gz
            initiat-linux-arm64.tar.gz
            initiat-windows-amd64.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
